-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2023-01-21 21:40:04 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE deo (
    iddeo    NUMBER NOT NULL,
    nazivdeo VARCHAR2(30) NOT NULL
);

ALTER TABLE deo ADD CONSTRAINT deo_pk PRIMARY KEY ( iddeo );

CREATE TABLE dobavljac (
    idrad NUMBER NOT NULL,
    email VARCHAR2(40)
);

ALTER TABLE dobavljac ADD CONSTRAINT dobavljac_pk PRIMARY KEY ( idrad );

CREATE TABLE firma (
    idfirm    NUMBER NOT NULL,
    nazivfirm VARCHAR2(50) NOT NULL,
    adrfirm   VARCHAR2(150)
);

ALTER TABLE firma ADD CONSTRAINT firma_pk PRIMARY KEY ( idfirm );

CREATE TABLE krojac (
    idrad     NUMBER NOT NULL,
    tipmasine VARCHAR2(50)
);

ALTER TABLE krojac ADD CONSTRAINT krojac_pk PRIMARY KEY ( idrad );

CREATE TABLE nabavlja (
    dobavljac_idrad NUMBER NOT NULL,
    sirovina_idsir  NUMBER NOT NULL
);

ALTER TABLE nabavlja ADD CONSTRAINT nabavlja_pk PRIMARY KEY ( dobavljac_idrad,
                                                              sirovina_idsir );

CREATE TABLE nudi (
    cena              NUMBER,
    proizvod_idpro    NUMBER NOT NULL,
    prodavnica_idprod NUMBER NOT NULL,
    nudi_id           NUMBER NOT NULL
);

ALTER TABLE nudi ADD CONSTRAINT nudi_pk PRIMARY KEY ( nudi_id );

CREATE TABLE odelenje (
    idodelenja          NUMBER NOT NULL,
    nazivodel           VARCHAR2(50),
    odelenje_idodelenja NUMBER,
    poslovodja_idposl   NUMBER,
    firma_idfirm        NUMBER
);

ALTER TABLE odelenje ADD CONSTRAINT odelenje_pk PRIMARY KEY ( idodelenja );

CREATE TABLE poslovodja (
    idposl  NUMBER NOT NULL,
    imeposl VARCHAR2(30) NOT NULL,
    przposl VARCHAR2(50) NOT NULL
);

ALTER TABLE poslovodja ADD CONSTRAINT poslovodja_pk PRIMARY KEY ( idposl );

CREATE TABLE pravi (
    krojac_idrad   NUMBER NOT NULL,
    proizvod_idpro NUMBER NOT NULL
);

ALTER TABLE pravi ADD CONSTRAINT pravi_pk PRIMARY KEY ( krojac_idrad,
                                                        proizvod_idpro );

CREATE TABLE prodavac (
    idrad             NUMBER NOT NULL,
    email             VARCHAR2(40),
    prodavnica_idprod NUMBER
);

ALTER TABLE prodavac ADD CONSTRAINT prodavac_pk PRIMARY KEY ( idrad );

CREATE TABLE prodavnica (
    idprod  NUMBER NOT NULL,
    nazprod VARCHAR2(30) NOT NULL,
    adrprod VARCHAR2(50),
    brtel   VARCHAR2(20)
);

ALTER TABLE prodavnica ADD CONSTRAINT prodavnica_pk PRIMARY KEY ( idprod );

CREATE TABLE proizvod (
    idpro    NUMBER NOT NULL,
    nazivpro VARCHAR2(50) NOT NULL
);

ALTER TABLE proizvod ADD CONSTRAINT proizvod_pk PRIMARY KEY ( idpro );

CREATE TABLE prostorija (
    idpros    NUMBER NOT NULL,
    nazivpros VARCHAR2(20) NOT NULL,
    sprat     NUMBER
);

ALTER TABLE prostorija ADD CONSTRAINT prostorija_pk PRIMARY KEY ( idpros );

CREATE TABLE racun (
    idrac          NUMBER NOT NULL,
    prodavac_idrad NUMBER NOT NULL
);

ALTER TABLE racun ADD CONSTRAINT racun_pk PRIMARY KEY ( idrac,
                                                        prodavac_idrad );

CREATE TABLE radnik (
    idrad             NUMBER NOT NULL,
    imerad            VARCHAR2(30) NOT NULL,
    przrad            VARCHAR2(50) NOT NULL,
    tiprad            VARCHAR2(20) 
--  ERROR: VARCHAR2 size not specified 
     NOT NULL,
    poslovodja_idposl NUMBER
);

ALTER TABLE radnik
    ADD CONSTRAINT ch_inh_radnik CHECK ( tiprad IN ( 'Dobavljac', 'Krojac', 'Prodavac', 'Radnik', 'Spremac' ) );

ALTER TABLE radnik ADD CONSTRAINT radnik_pk PRIMARY KEY ( idrad );

CREATE TABLE sadrzi (
    deo_iddeo      NUMBER NOT NULL,
    sirovina_idsir NUMBER NOT NULL
);

ALTER TABLE sadrzi ADD CONSTRAINT sadrzi_pk PRIMARY KEY ( deo_iddeo,
                                                          sirovina_idsir );

CREATE TABLE sastoji (
    deo_iddeo      NUMBER NOT NULL,
    proizvod_idpro NUMBER NOT NULL
);

ALTER TABLE sastoji ADD CONSTRAINT sastoji_pk PRIMARY KEY ( deo_iddeo,
                                                            proizvod_idpro );

CREATE TABLE sirovina (
    idsir    NUMBER NOT NULL,
    nazivsir VARCHAR2(30) NOT NULL
);

ALTER TABLE sirovina ADD CONSTRAINT sirovina_pk PRIMARY KEY ( idsir );

CREATE TABLE sprema (
    spremac_idrad     NUMBER NOT NULL,
    prostorija_idpros NUMBER NOT NULL
);

ALTER TABLE sprema ADD CONSTRAINT sprema_pk PRIMARY KEY ( spremac_idrad,
                                                          prostorija_idpros );

CREATE TABLE spremac (
    idrad NUMBER NOT NULL,
    brtel VARCHAR2(20)
);

ALTER TABLE spremac ADD CONSTRAINT spremac_pk PRIMARY KEY ( idrad );

CREATE TABLE stavka (
    rbrst                NUMBER NOT NULL,
    kolicina             NUMBER,
    racun_idrac          NUMBER NOT NULL,
    racun_prodavac_idrad NUMBER NOT NULL,
    nudi_nudi_id         NUMBER
);

ALTER TABLE stavka ADD CONSTRAINT stavka_pk PRIMARY KEY ( rbrst );

ALTER TABLE dobavljac
    ADD CONSTRAINT dobavljac_radnik_fk FOREIGN KEY ( idrad )
        REFERENCES radnik ( idrad );

ALTER TABLE krojac
    ADD CONSTRAINT krojac_radnik_fk FOREIGN KEY ( idrad )
        REFERENCES radnik ( idrad );

ALTER TABLE nabavlja
    ADD CONSTRAINT nabavlja_dobavljac_fk FOREIGN KEY ( dobavljac_idrad )
        REFERENCES dobavljac ( idrad );

ALTER TABLE nabavlja
    ADD CONSTRAINT nabavlja_sirovina_fk FOREIGN KEY ( sirovina_idsir )
        REFERENCES sirovina ( idsir );

ALTER TABLE nudi
    ADD CONSTRAINT nudi_prodavnica_fk FOREIGN KEY ( prodavnica_idprod )
        REFERENCES prodavnica ( idprod );

ALTER TABLE nudi
    ADD CONSTRAINT nudi_proizvod_fk FOREIGN KEY ( proizvod_idpro )
        REFERENCES proizvod ( idpro );

ALTER TABLE odelenje
    ADD CONSTRAINT odelenje_firma_fk FOREIGN KEY ( firma_idfirm )
        REFERENCES firma ( idfirm );

ALTER TABLE odelenje
    ADD CONSTRAINT odelenje_odelenje_fk FOREIGN KEY ( odelenje_idodelenja )
        REFERENCES odelenje ( idodelenja );

ALTER TABLE odelenje
    ADD CONSTRAINT odelenje_poslovodja_fk FOREIGN KEY ( poslovodja_idposl )
        REFERENCES poslovodja ( idposl );

ALTER TABLE pravi
    ADD CONSTRAINT pravi_krojac_fk FOREIGN KEY ( krojac_idrad )
        REFERENCES krojac ( idrad );

ALTER TABLE pravi
    ADD CONSTRAINT pravi_proizvod_fk FOREIGN KEY ( proizvod_idpro )
        REFERENCES proizvod ( idpro );

ALTER TABLE prodavac
    ADD CONSTRAINT prodavac_prodavnica_fk FOREIGN KEY ( prodavnica_idprod )
        REFERENCES prodavnica ( idprod );

ALTER TABLE prodavac
    ADD CONSTRAINT prodavac_radnik_fk FOREIGN KEY ( idrad )
        REFERENCES radnik ( idrad );

ALTER TABLE racun
    ADD CONSTRAINT racun_prodavac_fk FOREIGN KEY ( prodavac_idrad )
        REFERENCES prodavac ( idrad );

ALTER TABLE radnik
    ADD CONSTRAINT radnik_poslovodja_fk FOREIGN KEY ( poslovodja_idposl )
        REFERENCES poslovodja ( idposl );

ALTER TABLE sadrzi
    ADD CONSTRAINT sadrzi_deo_fk FOREIGN KEY ( deo_iddeo )
        REFERENCES deo ( iddeo );

ALTER TABLE sadrzi
    ADD CONSTRAINT sadrzi_sirovina_fk FOREIGN KEY ( sirovina_idsir )
        REFERENCES sirovina ( idsir );

ALTER TABLE sastoji
    ADD CONSTRAINT sastoji_deo_fk FOREIGN KEY ( deo_iddeo )
        REFERENCES deo ( iddeo );

ALTER TABLE sastoji
    ADD CONSTRAINT sastoji_proizvod_fk FOREIGN KEY ( proizvod_idpro )
        REFERENCES proizvod ( idpro );

ALTER TABLE sprema
    ADD CONSTRAINT sprema_prostorija_fk FOREIGN KEY ( prostorija_idpros )
        REFERENCES prostorija ( idpros );

ALTER TABLE sprema
    ADD CONSTRAINT sprema_spremac_fk FOREIGN KEY ( spremac_idrad )
        REFERENCES spremac ( idrad );

ALTER TABLE spremac
    ADD CONSTRAINT spremac_radnik_fk FOREIGN KEY ( idrad )
        REFERENCES radnik ( idrad );

ALTER TABLE stavka
    ADD CONSTRAINT stavka_nudi_fk FOREIGN KEY ( nudi_nudi_id )
        REFERENCES nudi ( nudi_id );

ALTER TABLE stavka
    ADD CONSTRAINT stavka_racun_fk FOREIGN KEY ( racun_idrac,
                                                 racun_prodavac_idrad )
        REFERENCES racun ( idrac,
                           prodavac_idrad );

CREATE OR REPLACE TRIGGER arc_fkarc_1_krojac BEFORE
    INSERT OR UPDATE OF idrad ON krojac
    FOR EACH ROW
DECLARE
    d VARCHAR2;
BEGIN
    SELECT
        a.tiprad
    INTO d
    FROM
        radnik a
    WHERE
        a.idrad = :new.idrad;

    IF ( d IS NULL OR d <> 'Krojac' ) THEN
        raise_application_error(-20223, 'FK Krojac_Radnik_FK in Table Krojac violates Arc constraint on Table Radnik - discriminator column tipRad doesn''t have value ''Krojac'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER arc_fkarc_1_dobavljac BEFORE
    INSERT OR UPDATE OF idrad ON dobavljac
    FOR EACH ROW
DECLARE
    d VARCHAR2;
BEGIN
    SELECT
        a.tiprad
    INTO d
    FROM
        radnik a
    WHERE
        a.idrad = :new.idrad;

    IF ( d IS NULL OR d <> 'Dobavljac' ) THEN
        raise_application_error(-20223, 'FK Dobavljac_Radnik_FK in Table Dobavljac violates Arc constraint on Table Radnik - discriminator column tipRad doesn''t have value ''Dobavljac'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER arc_fkarc_1_prodavac BEFORE
    INSERT OR UPDATE OF idrad ON prodavac
    FOR EACH ROW
DECLARE
    d VARCHAR2;
BEGIN
    SELECT
        a.tiprad
    INTO d
    FROM
        radnik a
    WHERE
        a.idrad = :new.idrad;

    IF ( d IS NULL OR d <> 'Prodavac' ) THEN
        raise_application_error(-20223, 'FK Prodavac_Radnik_FK in Table Prodavac violates Arc constraint on Table Radnik - discriminator column tipRad doesn''t have value ''Prodavac'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER arc_fkarc_1_spremac BEFORE
    INSERT OR UPDATE OF idrad ON spremac
    FOR EACH ROW
DECLARE
    d VARCHAR2;
BEGIN
    SELECT
        a.tiprad
    INTO d
    FROM
        radnik a
    WHERE
        a.idrad = :new.idrad;

    IF ( d IS NULL OR d <> 'Spremac' ) THEN
        raise_application_error(-20223, 'FK Spremac_Radnik_FK in Table Spremac violates Arc constraint on Table Radnik - discriminator column tipRad doesn''t have value ''Spremac'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE SEQUENCE nudi_nudi_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER nudi_nudi_id_trg BEFORE
    INSERT ON nudi
    FOR EACH ROW
    WHEN ( new.nudi_id IS NULL )
BEGIN
    :new.nudi_id := nudi_nudi_id_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            21
-- CREATE INDEX                             0
-- ALTER TABLE                             46
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           5
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          1
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   1
-- WARNINGS                                 0
